import localFont from "next/font/local";
import Header from "../components/Header";
import "./globals.css";

const myFont = localFont({
  src: "../../public/fonts/HeyWow-Medium.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
